from typing import Dict, Tuple, List

from .base_enum_meta import BaseEnumMeta


class LlmArtefactTypes(BaseEnumMeta):
    _INTERNAL_NONE = "none", -1, "none", "Internal placeholder for no specific language"
    NONE = "none", 0, "none,null,nil", "None selectd"
    INPUT = "input"
    USER_INPUT = "user_input"
    REFERENCE = "reference"
    UNKNOWN = "unknown", 999, "unknown", "Llm Artefact could not be identified"




class LlmArtefactTypes_One(BaseEnumMeta):
    # --- Core & Foundational ---
    _INTERNAL_NONE = "internal_none", -1, "_none", "Internal placeholder for no specific language/artefact"
    NONE = "none", 0, "null,nil", "No specific artefact type selected or applicable"
    UNKNOWN = "unknown", 999, "unidentified,other", "Llm Artefact type could not be identified or is not listed"

    # --- Input & Prompting (PE Focus) ---
    INPUT = "input", 1, "raw_input,user_query", "Raw input data or query from the user/system before processing"
    PROMPT = "prompt", 2, "instruction,full_prompt", "The complete textual instruction given to the LLM"
    PROMPT_TEMPLATE = "prompt_template", 3, "template,prompt_structure", "A parameterized structure for generating prompts"
    SYSTEM_PROMPT = "system_prompt", 4, "system_message,persona_prompt", "Instructions setting the LLM's behavior, persona, or role"
    USER_PROMPT = "user_prompt", 5, "user_message,query_prompt", "The specific question or task from the user within a conversation"
    CONTEXT = "context", 6, "retrieved_context,background_info", "Supporting information or documents provided to the LLM with the prompt (e.g., RAG)"
    FEW_SHOT_EXAMPLE = "few_shot_example", 7, "in_context_example,demonstration", "Example input-output pair(s) provided in the prompt for in-context learning"
    EXAMPLE_INPUT = "example_input", 8, "shot_input,demo_input", "The input part of a few-shot example"
    EXAMPLE_OUTPUT = "example_output", 9, "shot_output,demo_output", "The desired output part of a few-shot example"
    PROMPT_PARAMETERS = "prompt_parameters", 10, "template_variables,placeholders", "Variables or parameters used to fill a prompt template"

    # --- LLM Output & Generation ---
    OUTPUT = "output", 20, "llm_response,generation,completion", "The primary textual output generated by the LLM"
    RAW_OUTPUT = "raw_output", 21, "unprocessed_output,model_logits_text", "The direct, unprocessed text from the LLM before any parsing or cleaning"
    PARSED_OUTPUT = "parsed_output", 22, "structured_output,extracted_data", "Output that has been processed or parsed into a structured format (e.g., JSON)"
    CHAIN_OF_THOUGHT = "chain_of_thought", 23, "cot,reasoning_steps", "Intermediate reasoning steps generated by the LLM (can be part of prompt or output)"
    STREAMED_CHUNK = "streamed_chunk", 24, "output_token_stream,partial_response", "A segment of a streamed LLM output"
    FUNCTION_CALL = "function_call", 25, "tool_call,api_request_llm", "LLM output indicating a request to call an external function/tool"
    TOOL_CALL = "tool_call", 26, "agent_tool_call", "A more generic term for LLM-invoked tool usage (often structured)" # Overlaps with FUNCTION_CALL

    # --- Reference & Evaluation ---
    REFERENCE = "reference", 40, "ground_truth,expected_output,label", "The ground truth or target answer/output for evaluation"
    EVALUATION_RESULT = "evaluation_result", 41, "metric_score,assessment", "The outcome of an evaluation, including scores and/or qualitative feedback"
    SCORE = "score", 42, "metric_value,quantitative_eval", "A specific numerical score from an evaluation metric"
    EVALUATION_METRIC = "evaluation_metric", 43, "metric_definition,eval_criteria", "The definition or configuration of a metric used for evaluation (e.g., BLEU, ROUGE)"
    HUMAN_FEEDBACK = "human_feedback", 44, "annotation,human_rating,correction", "Feedback provided by a human annotator or evaluator"
    COMPARISON_RESULT = "comparison_result", 45, "a_b_test_result,preference_data", "Result of comparing two or more LLM outputs or prompts"
    BENCHMARK_DATA = "benchmark_data", 46, "test_suite,standard_eval_set", "A standardized dataset used for benchmarking LLM performance"

    # --- Data & Knowledge ---
    DATASET = "dataset", 60, "corpus,data_collection", "A collection of data used for training, fine-tuning, or evaluation"
    TRAINING_DATA = "training_data", 61, "fine_tuning_set,instruction_set", "Data specifically used for training or fine-tuning an LLM"
    VALIDATION_DATA = "validation_data", 62, "dev_set", "Data used to validate model performance during training/development"
    TEST_DATA = "test_data", 63, "holdout_set", "Data used for final unbiased evaluation of a trained model"
    INSTRUCTION_DATA = "instruction_data", 64, "prompt_response_pairs", "Dataset formatted as instruction-response pairs for fine-tuning"
    KNOWLEDGE_BASE_CHUNK = "knowledge_base_chunk", 65, "document_segment,retrieved_doc", "A chunk or segment from a knowledge base (e.g., for RAG)"
    EMBEDDING_VECTOR = "embedding_vector", 66, "text_embedding,vector_representation", "Numerical vector representation of text"
    TOKEN_SEQUENCE = "token_sequence", 67, "tokenized_text,input_ids", "A sequence of tokens representing text, often as integer IDs"

    # --- Model & Configuration ---
    MODEL_CONFIG = "model_config", 80, "hyperparameters,model_settings", "Configuration parameters for the LLM (e.g., temperature, max_tokens, model_name)"
    MODEL_WEIGHTS = "model_weights", 81, "model_parameters,checkpoint", "The learned parameters or weights of an LLM"
    MODEL_ARCHITECTURE = "model_architecture", 82, "network_structure,model_spec", "Specification of the LLM's architecture"
    TOKENIZER_CONFIG = "tokenizer_config", 83, "tokenizer_settings,vocab_file", "Configuration for the tokenizer, including vocabulary"

    # --- Prompt Engineering Lifecycle & Experimentation ---
    PROMPT_VERSION = "prompt_version", 100, "prompt_iteration", "A specific version or iteration of a prompt"
    EXPERIMENT_CONFIG = "experiment_config", 101, "run_parameters,trial_setup", "Configuration for a PE experiment or run"
    EXPERIMENT_RESULT = "experiment_result", 102, "trial_outcome,run_summary", "Aggregated results and artifacts from a PE experiment"
    PROMPT_CHAIN = "prompt_chain", 103, "sequence_of_prompts,llm_workflow", "A sequence of interconnected prompts or LLM calls"
    AGENT_PLAN = "agent_plan", 104, "task_decomposition,action_sequence", "A plan or sequence of actions generated by an LLM-based agent"
    AGENT_STATE = "agent_state", 105, "scratchpad,memory_context", "The internal state or memory of an LLM-based agent"
    TOOL_DEFINITION = "tool_definition", 106, "function_schema,api_spec_for_llm", "Schema or description of a tool/function available to the LLM"
    TOOL_RESPONSE = "tool_response", 107, "function_output,api_result", "The output or result from executing a tool/function call"

    # --- Operational & Logging ---
    INTERACTION_LOG = "interaction_log", 120, "conversation_history,chat_log", "A log of interactions between a user/system and the LLM"
    ERROR_LOG = "error_log", 121, "exception_trace,failure_report", "Log of errors or exceptions encountered during LLM interaction or processing"
    CACHE_ENTRY = "cache_entry", 122, "cached_response,memoized_result", "A cached LLM response or computation result"
    METADATA = "metadata", 123, "tags,attributes,contextual_info", "Additional information or attributes describing another artefact"

    # --- NLP Specific (pre-LLM or components used by LLMs) ---
    TEXT_DOCUMENT = "text_document", 140, "raw_text,document_content", "A piece of text, like a document or article"
    CORPUS = "corpus", 141, "text_collection,document_set", "A large collection of text documents" # Similar to DATASET but often raw text
    ANNOTATED_TEXT = "annotated_text", 142, "labeled_text,ner_tags,pos_tags", "Text with linguistic annotations (e.g., POS, NER, sentiment)"
    LEXICON = "lexicon", 143, "dictionary,word_list,gazetteer", "A vocabulary or list of words, possibly with associated information"
    GRAMMAR = "grammar", 144, "parsing_rules,syntax_rules", "Formal rules describing the syntax of a language"
    TRANSLATION = "translation", 145, "translated_text", "Text translated from one language to another"
    SUMMARY = "summary", 146, "text_summary,abstract", "A condensed version of a longer text"
    SENTIMENT_LABEL = "sentiment_label", 147, "polarity,emotion_tag", "Label indicating the sentiment (positive, negative, neutral) or emotion"
    TOPIC_MODEL = "topic_model", 148, "lda_result,topic_distribution", "A model representing latent topic in a collection of documents"
    KEYPHRASES = "keyphrases", 149, "keywords,extracted_terms", "Important phrases or terms extracted from text"

    # --- Safety & Guardrails ---
    GUARDRAIL_POLICY = "guardrail_policy", 160, "safety_rules,content_filter_config", "Configuration for safety mechanisms or content filters"
    GUARDRAIL_TRIGGER = "guardrail_trigger", 161, "safety_violation,filter_hit", "Indication that a guardrail or safety filter was activated"
    REDACTED_TEXT = "redacted_text", 162, "sanitized_output,pii_removed", "Text that has had sensitive information removed or masked"
    BIAS_ANALYSIS_REPORT = "bias_analysis_report", 163, "fairness_assessment", "Report detailing analysis of biases in model inputs or outputs"

    # --- Miscellaneous ---
    SESSION_ID = "session_id", 180, "conversation_id,interaction_key", "Identifier for a specific user session or conversation"
    USER_PROFILE = "user_profile", 181, "user_preferences,user_history", "Information about the user interacting with the LLM"
    IMAGE_INPUT = "image_input", 182, "visual_prompt,multimodal_image", "An image provided as input to a multimodal LLM" # For Multimodal
    AUDIO_INPUT = "audio_input", 183, "speech_input,multimodal_audio", "Audio data provided as input to a multimodal LLM" # For Multimodal
    VIDEO_INPUT = "video_input", 184, "visual_audio_prompt,multimodal_video", "Video data provided as input" # For Multimodal
    MULTIMODAL_OUTPUT = "multimodal_output", 185, "image_generation_llm,audio_generation_llm", "Non-textual output from an LLM (e.g., generated image, audio)"




class LlmArtefactTypes_4(BaseEnumMeta):
    # --- System & Control ---
    _INTERNAL_NONE = "none", -1, "none", "Internal placeholder for no specific language or type"
    NONE = "none", 0, "none,null,nil", "No specific artefact type selected or applicable"
    UNKNOWN = "unknown", 999, "unknown", "Llm Artefact type could not be identified or is not yet categorized"

    # --- Core Inputs ---
    INPUT = "input", 1, "input_data", "Generic input data to a system or model"
    USER_INPUT = "user_input", 2, "user_query,user_text", "Direct input provided by an end-user"
    PROMPT = "prompt", 3, "llm_prompt,instruction_prompt", "The specific text input designed to elicit a response from an LLM"
    QUERY = "query", 4, "search_query,database_query", "A specific question or request for information"
    INSTRUCTION = "instruction", 5, "task_instruction,command", "A directive telling the model what to do"
    CONTEXT_TEXT = "context_text", 6, "background_text,contextual_information", "Supplementary text provided to the LLM to inform its response"
    DOCUMENT_TEXT = "document_text", 7, "source_document,full_document", "A complete document used as input (e.g., for summarization, RAG)"
    REFERENCE_TEXT = "reference_text", 8, "ground_truth_text,gold_standard_text", "A human-verified or ideal text used for comparison or evaluation"
    FEW_SHOT_EXAMPLE_SET = "few_shot_example_set", 9, "in_context_examples,demonstrations", "A set of examples provided within a prompt to guide LLM behavior"
    ZERO_SHOT_INSTRUCTION = "zero_shot_instruction", 10, "direct_instruction", "An instruction for a task without providing examples"
    SYSTEM_PROMPT = "system_prompt", 11, "pre_prompt,system_message,role_definition", "Initial instructions defining the LLM's role, persona, or overarching rules"
    KNOWLEDGE_BASE_CHUNK = "knowledge_base_chunk", 12, "retrieved_document_chunk,rag_context", "A segment of text retrieved from a knowledge base to augment a prompt"
    IMAGE_INPUT = "image_input", 13, "input_image,visual_data", "Image data provided to a multimodal LLM"
    AUDIO_INPUT = "audio_input", 14, "input_audio,speech_data", "Audio data provided to a multimodal LLM or speech-to-text system"
    VIDEO_INPUT = "video_input", 15, "input_video,video_data", "Video data provided to a multimodal LLM"
    TABULAR_DATA_INPUT = "tabular_data_input", 16, "csv_input,excel_input", "Structured table data provided as input"
    CODE_INPUT = "code_input", 17, "source_code_input,script_input", "Computer code provided as input for generation, explanation, or debugging"

    # --- Core Outputs ---
    MODEL_OUTPUT_RAW = "model_output_raw", 50, "raw_llm_response,unprocessed_output", "The direct, unprocessed text output from the LLM"
    GENERATED_TEXT = "generated_text", 51, "llm_response,completion,generated_content", "Text generated by the LLM as a response or continuation"
    GENERATED_CODE = "generated_code", 52, "llm_generated_code,code_snippet", "Computer code generated by the LLM"
    GENERATED_IMAGE = "generated_image", 53, "output_image,ai_art", "Image data generated by a multimodal LLM or image generation model"
    GENERATED_AUDIO = "generated_audio", 54, "output_audio,synthesized_speech", "Audio data generated by an LLM or text-to-speech system"
    GENERATED_VIDEO = "generated_video", 55, "output_video,ai_video", "Video data generated by an LLM or video generation model"
    SUMMARY = "summary", 56, "text_summary,abstract", "A condensed version of a longer text, generated by an LLM"
    TRANSLATION = "translation", 57, "translated_text,machine_translation_output", "Text translated from one language to another by an LLM"
    ANSWER = "answer", 58, "qa_answer,response_to_query", "A direct answer to a question, generated by an LLM"
    CLASSIFICATION_LABEL = "classification_label", 59, "category_label,sentiment_label,tag", "A label assigned by an LLM for a classification task (e.g., sentiment, topic)"
    EXTRACTED_ENTITY = "extracted_entity", 60, "named_entity,ner_output", "An entity (e.g., person, organization, location) identified and extracted by an LLM"
    EXTRACTED_RELATION = "extracted_relation", 61, "relation_extraction_output,semantic_triple", "A relationship identified between entities"
    STRUCTURED_OUTPUT_JSON = "structured_output_json", 62, "json_data,parsed_data_json", "Data generated by an LLM in JSON format"
    STRUCTURED_OUTPUT_XML = "structured_output_xml", 63, "xml_data,parsed_data_xml", "Data generated by an LLM in XML format"
    STRUCTURED_OUTPUT_YAML = "structured_output_yaml", 64, "yaml_data,parsed_data_yaml", "Data generated by an LLM in YAML format"
    CHAIN_OF_THOUGHT = "chain_of_thought", 65, "cot_reasoning,reasoning_steps", "Intermediate reasoning steps generated by an LLM to arrive at an answer"
    PLAN_STEPS = "plan_steps", 66, "action_plan,task_decomposition", "A sequence of steps or actions planned by an LLM to achieve a goal"
    TOOL_CALL = "tool_call", 67, "function_call,api_request_generation", "A request generated by an LLM to call an external tool or API"
    TOOL_RESPONSE = "tool_response", 68, "api_response_data,function_result", "The data returned from an external tool or API call, to be fed back to the LLM"
    REFINED_OUTPUT = "refined_output", 69, "post_processed_output,curated_output", "LLM output that has undergone post-processing or human review"
    DIALOG_TURN = "dialog_turn", 70, "conversation_exchange,utterance_pair", "A single user input and model response pair in a conversation"
    DIALOG_HISTORY = "dialog_history", 71, "conversation_log,chat_transcript", "The complete sequence of turns in a conversation"

    # --- Data & Corpora ---
    CORPUS_RAW = "corpus_raw", 100, "raw_text_corpus,unprocessed_dataset", "A large collection of raw text data"
    CORPUS_PREPROCESSED = "corpus_preprocessed", 101, "cleaned_corpus,normalized_dataset", "A corpus that has undergone cleaning and normalization"
    TOKENIZED_TEXT = "tokenized_text", 102, "tokens,token_sequence", "Text that has been broken down into individual tokens"
    EMBEDDING_VECTOR = "embedding_vector", 103, "text_embedding,vector_representation", "A numerical vector representation of text, words, or documents"
    FINE_TUNING_DATA_PAIR = "fine_tuning_data_pair", 104, "prompt_completion_pair,instruction_response_pair", "A pair of input (prompt/instruction) and desired output used for fine-tuning an LLM"
    FINE_TUNING_DATASET = "fine_tuning_dataset", 105, "training_dataset_ft,custom_dataset", "A collection of data pairs for fine-tuning"
    PRETRAINING_DATASET = "pretraining_dataset", 106, "foundational_training_data", "Massive dataset used for initial pretraining of an LLM"
    EVALUATION_DATASET = "evaluation_dataset", 107, "test_set,benchmark_dataset", "A dataset used to evaluate LLM performance"
    SYNTHETIC_DATA = "synthetic_data", 108, "generated_training_data,artificial_data", "Data generated by an AI (often another LLM) for training or testing"
    ADVERSARIAL_EXAMPLE = "adversarial_example", 109, "robustness_test_case,attack_vector", "Input designed to cause an LLM to make a mistake or behave unexpectedly"
    PARALLEL_CORPUS = "parallel_corpus", 110, "bilingual_corpus,translation_memory", "A corpus containing the same text in two or more languages"
    ANNOTATED_DATA = "annotated_data", 111, "labeled_data,human_annotated_corpus", "Data that has been enriched with human-provided labels or annotations"
    BENCHMARK_RESULT_SET = "benchmark_result_set", 112, "evaluation_scores,leaderboard_data", "A collection of performance scores on a specific benchmark"

    # --- Model & Configuration ---
    MODEL_WEIGHTS = "model_weights", 150, "llm_parameters,checkpoint_file", "The learned parameters of an LLM"
    MODEL_CONFIG = "model_config", 151, "hyperparameters,model_architecture_spec", "Configuration file specifying model architecture, hyperparameters, etc."
    TOKENIZER_MODEL = "tokenizer_model", 152, "sentencepiece_model,bpe_model", "The model used for tokenizing text"
    VOCABULARY_FILE = "vocabulary_file", 153, "token_list,word_index", "A file listing the vocabulary known to the tokenizer/model"
    PROMPT_TEMPLATE = "prompt_template", 154, "template_string,f_string_prompt", "A reusable pattern for constructing prompts, often with placeholders"
    AGENT_DEFINITION = "agent_definition", 155, "llm_agent_config,tool_manifest", "Configuration defining an LLM-based agent, its tools, and its core logic"
    PERSONA_DEFINITION = "persona_definition", 156, "role_play_script,character_profile", "A detailed description of a persona for the LLM to adopt"
    SAFETY_POLICY = "safety_policy", 157, "content_filter_rules,guardrails_config", "Rules and configurations for ensuring safe and appropriate LLM outputs"
    QUANTIZED_MODEL = "quantized_model", 158, "compressed_model,low_precision_weights", "A version of an LLM with reduced precision weights for efficiency"
    MODEL_CARD = "model_card", 159, "model_documentation,transparency_report", "Document providing key information about an LLM (intended use, limitations, performance)"
    ADAPTER_WEIGHTS = "adapter_weights", 160, "lora_weights,peft_adapter", "Small set of trainable parameters for parameter-efficient fine-tuning (PEFT)"

    # --- Evaluation & Metrics ---
    EVALUATION_RESULT = "evaluation_result", 200, "performance_metric,score_report", "The outcome of an evaluation run, often including multiple metrics"
    METRIC_SCORE = "metric_score", 201, "bleu_score,rouge_score,accuracy", "A specific numerical score for an evaluation metric"
    HUMAN_EVALUATION_SCORE = "human_evaluation_score", 202, "human_rating,preference_score", "Score or feedback provided by a human evaluator"
    HUMAN_FEEDBACK_RLHF = "human_feedback_rlhf", 203, "preference_data,reward_model_training_data", "Human feedback (e.g., rankings, ratings) used for Reinforcement Learning from Human Feedback"
    EXPLANATION = "explanation", 204, "interpretability_output,saliency_map_data", "Output from an explainability technique (e.g., LIME, SHAP, attention visualization data)"
    CONFIDENCE_SCORE = "confidence_score", 205, "prediction_probability,uncertainty_measure", "A score indicating the model's confidence in its output"
    ERROR_ANALYSIS_REPORT = "error_analysis_report", 206, "failure_case_summary,mistake_pattern", "A report detailing types and patterns of errors made by the LLM"
    A_B_TEST_RESULT = "a_b_test_result", 207, "comparative_performance_data", "Results from an A/B test comparing different prompts, models, or configurations"

    # --- Logging & Monitoring ---
    LOG_ENTRY = "log_entry", 250, "application_log,trace_data", "A single record of an event or transaction within the LLM system"
    DEBUG_INFO = "debug_info", 251, "diagnostic_data,error_trace", "Information useful for debugging issues with LLM interactions"
    MONITORING_DATA_POINT = "monitoring_data_point", 252, "telemetry_data,usage_statistic", "A data point collected for monitoring LLM performance, usage, or health in production"
    LATENCY_MEASUREMENT = "latency_measurement", 253, "response_time_data", "Data on the time taken for an LLM to generate a response"
    COST_ESTIMATE = "cost_estimate", 254, "token_usage_cost,inference_cost", "Estimated cost associated with an LLM API call or generation"

    # --- Prompt Engineering Specific ---
    PROMPT_CHAIN = "prompt_chain", 300, "multi_step_prompt,sequential_prompts", "A sequence of prompts where the output of one feeds into the next"
    PROMPT_OPTIMIZATION_RESULT = "prompt_optimization_result", 301, "optimized_prompt_candidate,prompt_tuning_output", "The result of an automated prompt optimization process"
    PROMPT_VERSION = "prompt_version", 302, "prompt_iteration,prompt_revision", "A specific version of a prompt, used for tracking changes"
    EVALUATION_PAIR = "evaluation_pair", 303, "prompt_response_evaluation_pair", "A prompt and its corresponding model output, grouped for evaluation"
    PROMPT_INJECTION_ATTEMPT = "prompt_injection_attempt", 304, "malicious_prompt_input", "User input designed to subvert a prompt's original instructions"
    JAILBREAK_ATTEMPT = "jailbreak_attempt", 305, "policy_bypass_prompt", "User input designed to make the LLM violate its safety guidelines or intended use policies"

    # --- Knowledge Representation & Graphs ---
    KNOWLEDGE_GRAPH_TRIPLE = "knowledge_graph_triple", 350, "rdf_triple,subject_predicate_object", "A (subject, predicate, object) statement from a knowledge graph"
    KNOWLEDGE_GRAPH = "knowledge_graph", 351, "ontology_data,semantic_network", "A structured representation of knowledge as a graph"
    CONCEPT_MAP = "concept_map", 352, "mind_map_data", "A visual representation of concepts and their relationships, potentially generated or understood by an LLM"

    # --- User Interface & Interaction ---
    USER_SESSION_DATA = "user_session_data", 400, "interaction_log,clickstream_data_relevant_to_llm", "Data related to a user's interaction session with an LLM-powered application"
    UI_STATE_SNAPSHOT = "ui_state_snapshot", 401, "application_view_data", "A snapshot of the user interface state at the time of LLM interaction"
    USER_PREFERENCES = "user_preferences", 402, "personalization_settings", "User-defined settings or preferences that might influence LLM behavior"

    # --- Legal & Ethical ---
    DATA_USAGE_AGREEMENT = "data_usage_agreement", 450, "consent_form_llm", "Documentation outlining how user data will be used by the LLM system"
    BIAS_REPORT = "bias_report", 451, "fairness_assessment_document", "A report analyzing potential biases in the LLM or its training data"
    AUDIT_TRAIL_LLM = "audit_trail_llm", 452, "llm_activity_log,compliance_record", "A secure log of LLM interactions for auditing and compliance purposes"

    # --- Advanced / Research ---
    ATTENTION_WEIGHTS_VISUALIZATION = "attention_weights_visualization", 500, "attention_map,saliency_heatmap_attention", "Visual representation of model's attention mechanism"
    ACTIVATION_MAP = "activation_map", 501, "neuron_activation_pattern", "Data representing the activation of neurons or layers within the LLM"
    COUNTERFACTUAL_EXPLANATION = "counterfactual_explanation", 502, "what_if_scenario_output", "An explanation showing how small changes to input would change the output"
    REWARD_MODEL_OUTPUT = "reward_model_output", 503, "rlhf_reward_score", "The score assigned by a reward model in an RLHF setup"
    GENERATED_QUESTION = "generated_question", 504, "question_generation_output", "A question generated by an LLM, e.g., for data augmentation or study aids"
    TEXT_STYLE_TRANSFER_OUTPUT = "text_style_transfer_output", 505, "stylized_text", "Text whose style has been altered by an LLM (e.g. formal to informal)"
    ARGUMENT_MINING_OUTPUT = "argument_mining_output", 506, "claims_evidence_pairs", "Identified argumentative components (claims, premises) in text"

    # --- Placeholder for Future Expansion ---
    DOMAIN_SPECIFIC_ARTEFACT = "domain_specific_artefact", 900, "custom_artefact_type", "A placeholder for highly domain-specific artefacts not yet covered"
    # Add more as they become relevant...
    # The beauty of this is it can always be extended!


class LlmArtefactTypes(BaseEnumMeta):
    # --- System & Special Values ---
    _INTERNAL_NONE = "internal_none", -1, "none", "Internal placeholder for no specific language"
    NONE = "none", 0, "none,null,nil", "No specific artefact type selected or applicable"
    UNKNOWN = "unknown", 1, "undefined,unidentified", "Llm Artefact type could not be identified or is not yet categorized"
    ERROR_MESSAGE = "error_message", 2, "error,exception", "An error message or exception trace related to an LLM operation"
    METADATA = "metadata", 3, "info,details", "General metadata or supplementary information about another artefact"
    CONFIGURATION = "configuration", 4, "config,settings", "Configuration settings for a model, prompt, or system component"

    # --- Core Inputs to LLM ---
    INPUT = "input", 10, "general_input", "Generic input provided to a system or model"
    USER_INPUT = "user_input", 11, "user_query,query,end_user_input", "Input directly from an end-user interacting with the LLM"
    PROMPT = "prompt", 12, "llm_prompt,instruction_prompt", "The complete input string given to an LLM, including instructions, context, and query"
    SYSTEM_PROMPT = "system_prompt", 13, "system_message,system_instruction", "Initial instructions setting the context, role, or behavior for an LLM, especially in chat models"
    INSTRUCTION = "instruction", 14, "task_instruction,directive", "A specific directive or task description part of a prompt"
    CONTEXT = "context", 15, "background_information,contextual_data", "Background information or documents provided to the LLM to inform its generation"
    FEW_SHOT_EXAMPLE = "few_shot_example", 16, "demonstration,in_context_example,shot", "An example pair of (input, output) provided in the prompt to guide the LLM"
    ZERO_SHOT_INPUT = "zero_shot_input", 17, "unseen_input", "An input for which no direct examples were provided in the prompt"
    DOCUMENT = "document", 18, "text_document,source_document", "A source text document used as input or reference"
    KNOWLEDGE_BASE_SNIPPET = "knowledge_base_snippet", 19, "retrieved_document,rag_context,chunk", "A snippet or chunk retrieved from a knowledge base (e.g., for RAG)"
    USER_PROFILE = "user_profile", 20, "user_preferences,persona_data", "Information about the user to personalize LLM responses"
    SESSION_HISTORY = "session_history", 21, "chat_history,conversation_log", "Record of previous turns in a conversation"
    TOOL_DESCRIPTION = "tool_description", 22, "function_signature,api_spec", "Description of available tools or functions the LLM can call"

    # --- LLM Outputs & Generations ---
    OUTPUT = "output", 30, "llm_output,model_output,generation", "Generic output from a system or model"
    LLM_RESPONSE = "llm_response", 31, "model_response,generated_text,completion", "The primary text generated by the LLM"
    CANDIDATE_OUTPUT = "candidate_output", 32, "generation_candidate,beam_search_candidate", "One of multiple possible outputs generated by the LLM (e.g., from beam search or multiple samples)"
    SUMMARY = "summary", 33, "abstract,text_summary", "A condensed version of a longer text generated by an LLM"
    TRANSLATION = "translation", 34, "translated_text", "Text translated from one language to another by an LLM"
    GENERATED_CODE = "generated_code", 35, "code_snippet,program_code", "Software code generated by an LLM"
    ANSWER = "answer", 36, "qa_answer,response_to_question", "A direct answer to a question posed to the LLM"
    PLAN = "plan", 37, "action_plan,step_by_step_plan", "A sequence of steps or actions generated by an LLM to achieve a goal"
    REASONING_TRACE = "reasoning_trace", 38, "chain_of_thought,cot,thought_process", "Intermediate reasoning steps generated by the LLM to arrive at an answer"
    AGENT_THOUGHT = "agent_thought", 39, "agent_scratchpad,internal_monologue", "Internal thoughts or deliberations of an LLM-based agent"
    FUNCTION_CALL_REQUEST = "function_call_request", 40, "tool_call,api_call_request", "A structured request from the LLM to call an external tool or API"
    TOOL_RESPONSE_FOR_LLM = "tool_response_for_llm", 41, "function_result,api_response_to_llm", "The result from an external tool/API call, formatted to be fed back to the LLM"
    FORMATTED_OUTPUT = "formatted_output", 42, "structured_output,json_output,xml_output", "LLM output constrained to a specific format (e.g., JSON, XML)"
    EXTRACTED_INFORMATION = "extracted_information", 43, "entities,relations,slots", "Specific pieces of information extracted from text by an LLM (NER, RE, slot filling)"
    REPHRASED_TEXT = "rephrased_text", 44, "paraphrase,rewritten_text", "Text that has been reworded by an LLM while preserving meaning"
    DIALOG_TURN = "dialog_turn", 45, "conversation_turn", "A single utterance or exchange within a larger dialog"

    # --- Reference & Evaluation Artefacts ---
    REFERENCE = "reference", 50, "ground_truth,gold_standard,expected_output", "The ideal or correct output for a given input, used for evaluation"
    HUMAN_EVALUATION = "human_evaluation", 51, "human_rating,human_score,annotation", "Scores, ratings, or qualitative feedback provided by human evaluators"
    AUTOMATED_METRIC_SCORE = "automated_metric_score", 52, "metric_result,bleu,rouge,f1_score", "Scores from automated evaluation metrics (e.g., BLEU, ROUGE, F1)"
    EVALUATION_PROMPT = "evaluation_prompt", 53, "eval_prompt,judgement_prompt", "A prompt used to instruct an LLM (or human) on how to evaluate another LLM's output"
    EVALUATION_RESPONSE = "evaluation_response", 54, "eval_output,judgement_output", "The output from an LLM (or human) that is evaluating another LLM's output"
    FEEDBACK_USER = "feedback_user", 55, "user_rating,thumbs_up_down", "Feedback provided by the end-user on the LLM's output"
    CORRECTED_OUTPUT = "corrected_output", 56, "edited_output,post_edited_generation", "LLM output that has been manually corrected or improved"
    ERROR_ANALYSIS_REPORT = "error_analysis_report", 57, "failure_case,error_category", "A report detailing types and frequencies of errors made by the LLM"
    ADVERSARIAL_EXAMPLE = "adversarial_example", 58, "robustness_test_case,jailbreak_attempt", "Input designed to trick or mislead the LLM, or expose vulnerabilities"
    COUNTERFACTUAL_EXAMPLE = "counterfactual_example", 59, "what_if_scenario", "An input modified slightly from an original to test model sensitivity or reasoning"
    BENCHMARK_RESULT = "benchmark_result", 60, "leaderboard_score", "Performance score on a standardized benchmark dataset"

    # --- Prompt Engineering (PE) Specific Artefacts ---
    PROMPT_TEMPLATE = "prompt_template", 70, "template_string,f_string_prompt", "A parameterized structure for generating prompts"
    PROMPT_VERSION = "prompt_version", 71, "prompt_iteration,prompt_variant", "A specific version or iteration of a prompt design"
    PROMPT_COMPONENT = "prompt_component", 72, "instruction_block,context_block,example_block", "A modular part of a larger prompt (e.g., preamble, instructions, examples)"
    PROMPT_CHAIN = "prompt_chain", 73, "sequential_prompts,multi_step_prompt", "A sequence of prompts where the output of one feeds into the next"
    PROMPT_EVALUATION_METRIC = "prompt_evaluation_metric", 74, "pe_metric", "Metric specifically designed or used for evaluating prompt effectiveness"
    PROMPT_OPTIMIZATION_LOG = "prompt_optimization_log", 75, "prompt_tuning_history", "Log of attempts and results during automated or manual prompt optimization"
    PROMPT_NEGATIVES = "prompt_negatives", 76, "negative_constraints,undesired_outputs", "Examples or descriptions of what the LLM should *not* produce for a given prompt"

    # --- Data & Dataset Artefacts ---
    DATASET = "dataset", 80, "corpus,data_collection", "A collection of data instances"
    TRAINING_DATA = "training_data", 81, "train_set,instruction_tuning_data", "Data used to train or fine-tune an LLM"
    VALIDATION_DATA = "validation_data", 82, "dev_set,validation_set", "Data used to tune hyperparameters and evaluate models during development"
    TEST_DATA = "test_data", 83, "eval_set,holdout_set", "Data used for final, unbiased evaluation of a trained LLM"
    PREPROCESSED_DATA = "preprocessed_data", 84, "cleaned_data,tokenized_data", "Data that has undergone cleaning, tokenization, or other transformations"
    AUGMENTED_DATA = "augmented_data", 85, "synthetic_data,backtranslation_data", "Data created by augmenting existing data (e.g., paraphrasing, adding noise)"
    DATA_SAMPLE = "data_sample", 86, "instance,example_row", "A single instance or example from a dataset"
    DATA_SCHEMA = "data_schema", 87, "dataset_structure,column_description", "Description of the structure and format of a dataset"
    ANNOTATION_GUIDELINES = "annotation_guidelines", 88, "labeling_instructions", "Instructions provided to human annotators for labeling data"
    SYNTHETIC_DATASET_CONFIG = "synthetic_dataset_config", 89, "data_generation_prompt_template", "Configuration or prompt template used to generate synthetic data using an LLM"

    # --- Model Internals & Representations (Potentially more for NLP/research) ---
    TOKEN_IDS = "token_ids", 90, "input_ids,encoded_tokens", "Numerical representation of text after tokenization"
    EMBEDDING_VECTOR = "embedding_vector", 91, "word_embedding,sentence_embedding,document_embedding", "Dense vector representation of text"
    ATTENTION_WEIGHTS = "attention_weights", 92, "attention_matrix,attention_scores", "Weights indicating the importance of different input tokens for generating an output token"
    HIDDEN_STATE = "hidden_state", 93, "transformer_layer_output,internal_representation", "Internal activations or representations within the layers of an LLM"
    LOGITS = "logits", 94, "pre_softmax_scores,unnormalized_probabilities", "Raw, unnormalized scores output by the final layer of an LLM before softmax"
    PROBABILITY_DISTRIBUTION = "probability_distribution", 95, "token_probabilities,softmax_output", "Probability distribution over the vocabulary for the next token"
    VOCABULARY_FILE = "vocabulary_file", 96, "vocab,token_map", "Mapping between tokens and their numerical IDs"

    # --- Model & Training Artefacts ---
    MODEL_ARCHITECTURE = "model_architecture", 100, "network_design,model_spec", "Description of the LLM's architecture (e.g., layers, heads)"
    MODEL_WEIGHTS = "model_weights", 101, "parameters,checkpoint_file", "The learned parameters of an LLM"
    MODEL_CARD = "model_card", 102, "model_documentation,model_report", "Document providing comprehensive information about an LLM (use, limitations, evaluation)"
    TRAINING_LOG = "training_log", 103, "fine_tuning_log,loss_curve_data", "Log of metrics and events during model training or fine-tuning"
    HYPERPARAMETERS = "hyperparameters", 104, "training_config,learning_rate_schedule", "Configuration settings used for training or fine-tuning a model"
    OPTIMIZER_STATE = "optimizer_state", 105, "adam_state,gradient_accumulation", "State of the optimizer during training, allowing resumption"
    PEFT_ADAPTER = "peft_adapter", 106, "lora_weights,prompt_tuning_vectors", "Parameter-Efficient Fine-Tuning adapter weights (e.g., LoRA)"

    # --- Multimodal Artefacts ---
    IMAGE_INPUT = "image_input", 110, "input_image,visual_context", "An image provided as input to a multimodal LLM"
    AUDIO_INPUT = "audio_input", 111, "input_audio,speech_segment", "An audio clip provided as input to a multimodal LLM"
    VIDEO_INPUT = "video_input", 112, "input_video,video_frames", "A video provided as input to a multimodal LLM"
    GENERATED_IMAGE = "generated_image", 113, "output_image,ai_art", "An image generated by a multimodal LLM"
    GENERATED_AUDIO = "generated_audio", 114, "output_audio,synthesized_speech", "Audio generated by a multimodal LLM (e.g., text-to-speech)"
    IMAGE_CAPTION = "image_caption", 115, "visual_description", "A textual description of an image, potentially generated or used as input"
    AUDIO_TRANSCRIPT = "audio_transcript", 116, "speech_to_text_output", "Text transcribed from an audio input"

    # --- Operational & Deployment Artefacts ---
    API_REQUEST = "api_request", 120, "http_request,inference_request", "The full request made to an LLM API endpoint"
    API_RESPONSE = "api_response", 121, "http_response,inference_response", "The full response received from an LLM API endpoint"
    DEPLOYMENT_CONFIG = "deployment_config", 122, "serving_config,scaling_parameters", "Configuration for deploying and serving an LLM"
    USAGE_LOG = "usage_log", 123, "api_call_log,token_count_log", "Logs detailing the usage of an LLM service (e.g., number of calls, tokens processed)"
    MONITORING_DATA = "monitoring_data", 124, "performance_metrics,latency_data,drift_detection_signal", "Data collected for monitoring LLM performance and behavior in production"
    CACHE_ENTRY = "cache_entry", 125, "cached_response,memoized_result", "A stored response for a previously seen input to speed up future requests"
    SAFETY_FILTER_LOG = "safety_filter_log", 126, "content_moderation_output,guardrail_event", "Log or output from a safety filter or content moderation layer"
    AUDIT_TRAIL = "audit_trail", 127, "interaction_record,change_log", "A record of interactions, changes, or decisions made within an LLM system for accountability"

    # --- Research & Analysis Specific ---
    EXPERIMENT_CONFIGURATION = "experiment_configuration", 130, "research_setup,trial_params", "Configuration specific to a research experiment involving LLMs"
    EXPERIMENT_RESULTS = "experiment_results", 131, "findings,observations", "Outcome and data gathered from a research experiment"
    LITERATURE_REFERENCE = "literature_reference", 132, "citation,paper_link", "Reference to a scientific paper or publication"
    HYPOTHESIS = "hypothesis", 133, "research_question,assumption", "A testable statement or question being investigated"
    QUALITATIVE_ANALYSIS = "qualitative_analysis", 134, "thematic_analysis_notes,case_study_report", "Non-numerical analysis of LLM behavior or outputs"

    # --- Graph / Knowledge Graph Related Artefacts ---
    NODE = "node", 140, "entity_node,concept_node", "A node in a graph structure, potentially representing an entity or concept"
    EDGE = "edge", 141, "relationship,link,triple_arc", "A relationship or link between nodes in a graph"
    GRAPH_QUERY = "graph_query", 142, "sparql_query,cypher_query", "A query to retrieve information from a graph database"
    SUBGRAPH = "subgraph", 143, "graph_pattern,extracted_graph", "A portion of a larger graph"
    KNOWLEDGE_GRAPH = "knowledge_graph", 144, "ontology,semantic_network", "A structured representation of knowledge as a graph"

    # --- User Interface (UI) / User Experience (UX) related for LLM Apps ---
    UI_ELEMENT_STATE = "ui_element_state", 150, "button_state,dropdown_selection", "The state of a UI element in an LLM-powered application"
    USER_FLOW_TRACE = "user_flow_trace", 151, "click_stream,navigation_path", "Sequence of user interactions within an application"
    APPLICATION_LOG = "application_log", 152, "app_event_log", "General application-level logs that might contain LLM interaction context"

    # --- Final Placeholder ---
    PLACEHOLDER_FOR_FUTURE = "placeholder_for_future", 9999, "tbd,future_use", "Reserved for a future, yet undefined, artefact type"


class LlmArtefactTypes(metaclass=BaseEnumMeta):
    # --- Foundational & Control ---
    _INTERNAL_NONE = "internal_none", -1, "none", "Internal placeholder for no specific language or type"
    NONE = "none", 0, "none,null,nil", "No specific artefact type selected or applicable"
    UNKNOWN = "unknown", 1, "undefined,unidentified", "Llm Artefact type could not be identified"
    METADATA = "metadata", 2, "info,details", "Descriptive information about another artefact or process"
    CONFIGURATION = "configuration", 3, "config,settings", "Settings or parameters for a model, process, or system"
    SCHEMA = "schema", 4, "structure,format_definition", "Defines the structure or format of data (e.g., JSON schema for output)"

    # --- Input Artefacts ---
    INPUT = "input", 10, "raw_input", "General input to a system or process"
    USER_INPUT = "user_input", 11, "human_input,query", "Input provided directly by a human user"
    SYSTEM_INPUT = "system_input", 12, "automated_input", "Input generated by another system or automated process"

    # --- Prompt Engineering Specific Inputs ---
    PROMPT = "prompt", 20, "instruction_set", "The complete set of instructions and context given to an LLM"
    PROMPT_TEMPLATE = "prompt_template", 21, "template,skeleton", "A reusable structure for creating prompts, with placeholders"
    PROMPT_COMPONENT = "prompt_component", 22, "prompt_part,prompt_segment", "A distinct part of a larger prompt (e.g., persona, task, examples)"
    SYSTEM_PROMPT = "system_prompt", 23, "system_message,pre_prompt", "High-level instructions or context set for an LLM, often guiding its persona or overall behavior"
    USER_PROMPT = "user_prompt", 24, "user_query_for_llm", "The specific question or task part of the prompt, typically from the user"
    ASSISTANT_PROMPT = "assistant_prompt", 25, "model_prompt_segment", "A segment in a prompt representing a previous turn from the assistant/LLM, used for context or few-shot examples."
    INSTRUCTION = "instruction", 26, "task_instruction,directive", "A specific directive or command within a prompt"
    CONTEXT = "context", 27, "background_info,supplementary_data", "Background information or data provided to the LLM to inform its response"
    FEW_SHOT_EXAMPLE = "few_shot_example", 28, "in_context_example,demonstration", "An input-output pair provided within the prompt to guide the LLM's behavior"
    FEW_SHOT_EXAMPLE_INPUT = "few_shot_example_input", 29, "example_query,example_stimulus", "The input part of a few-shot example"
    FEW_SHOT_EXAMPLE_OUTPUT = "few_shot_example_output", 30, "example_response,example_completion", "The desired output part of a few-shot example"
    PERSONA_DEFINITION = "persona_definition", 31, "role_description,actor_profile", "Description of the persona the LLM should adopt"
    TASK_DESCRIPTION = "task_description", 32, "objective_statement,goal_definition", "A clear statement of the task the LLM needs to perform"
    OUTPUT_FORMAT_SPECIFICATION = "output_format_specification", 33, "format_constraint,output_schema_prompt", "Instructions on how the output should be structured (e.g., JSON, XML, list)"
    CONSTRAINT = "constraint", 34, "limitation,rule,guideline", "Rules or limitations the LLM must adhere to (e.g., length, topic to avoid)"
    NEGATIVE_PROMPT = "negative_prompt", 35, "anti_prompt,exclusion_criteria", "Instructions about what the LLM should *not* do or generate"
    TOOL_DEFINITION = "tool_definition", 36, "function_signature,api_spec_for_llm", "Description of a tool or function the LLM can choose to call"
    KNOWLEDGE_BASE_SNIPPET = "knowledge_base_snippet", 37, "retrieved_document,rag_chunk", "A piece of text retrieved from a knowledge base to augment the prompt (RAG)"

    # --- Output Artefacts ---
    OUTPUT = "output", 50, "raw_output,generation", "General output from a system or process"
    MODEL_RESPONSE = "model_response", 51, "llm_output,generated_text,completion", "The direct text or structured output generated by an LLM"
    RAW_MODEL_RESPONSE = "raw_model_response", 52, "unprocessed_llm_output", "The output from the LLM before any post-processing"
    PROCESSED_MODEL_RESPONSE = "processed_model_response", 53, "cleaned_llm_output,parsed_llm_output", "LLM output after cleaning, parsing, or other transformations"
    SUMMARY = "summary", 54, "abstract,synopsis", "A condensed version of a longer text, generated by an LLM"
    TRANSLATION = "translation", 55, "translated_text", "Text converted from one language to another by an LLM"
    CODE_SNIPPET = "code_snippet", 56, "generated_code,script", "A piece of programming code generated by an LLM"
    JSON_OUTPUT = "json_output", 57, "generated_json", "Output from an LLM specifically formatted as JSON"
    XML_OUTPUT = "xml_output", 58, "generated_xml", "Output from an LLM specifically formatted as XML"
    YAML_OUTPUT = "yaml_output", 59, "generated_yaml", "Output from an LLM specifically formatted as YAML"
    MARKDOWN_OUTPUT = "markdown_output", 60, "generated_markdown", "Output from an LLM formatted in Markdown"
    ANSWER = "answer", 61, "query_response", "A direct response to a question"
    QUESTION_GENERATED = "question_generated", 62, "llm_generated_query", "A question generated by an LLM (e.g., for clarification, or for search)"
    PLAN = "plan", 63, "action_plan,step_sequence,reasoning_trace_plan", "A sequence of steps or actions generated by an LLM to achieve a goal"
    CRITIQUE = "critique", 64, "evaluation_text,feedback_text", "An assessment or review generated by an LLM (e.g., of its own output or another piece of text)"
    TOOL_CALL = "tool_call", 65, "function_call_request,api_invocation", "The LLM's decision to use a specific tool, including parameters"
    TOOL_CALL_ARGUMENTS = "tool_call_arguments", 66, "function_parameters,tool_inputs", "The arguments/parameters for a tool/function call, as decided by the LLM"
    TOOL_RESPONSE = "tool_response", 67, "function_output,api_result_for_llm", "The result returned from executing a tool/function, to be fed back to the LLM"
    CHAIN_OF_THOUGHT = "chain_of_thought", 68, "cot,reasoning_steps,rationale", "Intermediate reasoning steps generated by an LLM before the final answer"
    TREE_OF_THOUGHT_NODE = "tree_of_thought_node", 69, "tot_node,thought_branch", "A state or thought in a Tree of Thoughts exploration process"
    DIALOG_TURN = "dialog_turn", 70, "conversation_exchange,utterance_pair", "A single user input and model response pair in a conversation"
    HALLUCINATION = "hallucination", 71, "fabricated_info,misinformation", "An output from the LLM that is factually incorrect or nonsensical but presented confidently"
    REPHRASED_TEXT = "rephrased_text", 72, "paraphrase,rewritten_content", "Text that has been rewritten by the LLM to convey the same meaning in different words"
    KEYWORDS = "keywords", 73, "tags,key_phrases", "Important terms or phrases extracted or generated by the LLM"
    NAMED_ENTITIES = "named_entities", 74, "ner_output,entities", "Named entities (like persons, organizations, locations) identified by the LLM"
    SENTIMENT = "sentiment", 75, "sentiment_label,opinion", "Sentiment (positive, negative, neutral) classified by the LLM"
    CLASSIFICATION_LABEL = "classification_label", 76, "category_tag,class_prediction", "A category or class assigned to an input by the LLM"

    # --- Data for Training, Fine-tuning, Evaluation ---
    DATASET = "dataset", 100, "corpus,data_collection", "A collection of data used for training, validation, or testing"
    TRAINING_DATA = "training_data", 101, "train_set", "Data used to train or fine-tune a model"
    VALIDATION_DATA = "validation_data", 102, "dev_set,val_set", "Data used to tune hyperparameters and evaluate models during training"
    TEST_DATA = "test_data", 103, "eval_set,holdout_set", "Data used for final evaluation of a trained model's performance"
    FINE_TUNING_DATASET = "fine_tuning_dataset", 104, "instruction_dataset,sft_data", "Dataset specifically prepared for supervised fine-tuning of an LLM"
    PREFERENCE_DATASET = "preference_dataset", 105, "rlhf_data,comparison_data", "Dataset containing pairs of responses with human (or model) preferences, used for RLHF"
    REFERENCE = "reference", 106, "ground_truth,golden_standard,label", "The correct or ideal output for a given input, used for evaluation or training"
    ANNOTATION = "annotation", 107, "human_label,markup", "Metadata or labels added to data by humans (or models)"
    PREDICTION = "prediction", 108, "model_forecast,inference_result", "The model's output when trying to match a reference or label"

    # --- Evaluation & Metrics ---
    EVALUATION_RESULT = "evaluation_result", 120, "performance_score,benchmark_outcome", "The outcome of an evaluation process, often including metrics"
    EVALUATION_METRIC = "evaluation_metric", 121, "score,metric_value", "A specific quantitative measure of performance (e.g., BLEU, ROUGE, F1, accuracy)"
    HUMAN_EVALUATION_SCORE = "human_evaluation_score", 122, "annotator_rating,human_score", "A score or rating assigned by a human evaluator"
    MODEL_GRADE = "model_grade", 123, "llm_as_judge_score,ai_critique_score", "A score or evaluation provided by another LLM acting as a judge"
    BENCHMARK_RESULT = "benchmark_result", 124, "standard_test_score", "Performance results on a standardized benchmark dataset/task"

    # --- Internal Model & Process Artefacts ---
    TOKEN_IDS = "token_ids", 140, "input_ids,encoded_tokens", "Numerical representation of text after tokenization"
    TOKEN_TEXT = "token_text", 141, "decoded_tokens,subwords", "The actual text segments corresponding to token IDs"
    EMBEDDING_VECTOR = "embedding_vector", 142, "text_embedding,dense_vector", "Numerical vector representation of text, capturing semantic meaning"
    ATTENTION_MASK = "attention_mask", 143, "padding_mask", "Mask indicating which tokens should be attended to by the model"
    ATTENTION_WEIGHTS = "attention_weights", 144, "self_attention_scores,cross_attention_scores", "Weights indicating the importance of different tokens when computing representations"
    HIDDEN_STATE = "hidden_state", 145, "encoder_state,decoder_state,llm_layer_output", "Internal representation of data at a specific layer of the neural network"
    LOGITS = "logits", 146, "unnormalized_probabilities,scores_before_softmax", "Raw output scores from the model for each possible token in the vocabulary, before normalization"
    PROBABILITIES = "probabilities", 147, "token_probabilities,softmax_output", "Normalized probabilities for each possible next token"
    MODEL_WEIGHTS = "model_weights", 148, "parameters,checkpoint", "The learnable parameters of the LLM"
    MODEL_ARCHITECTURE = "model_architecture", 149, "network_structure,model_definition", "The definition of the LLM's structure (layers, connections, etc.)"
    DISTILLED_KNOWLEDGE = "distilled_knowledge", 150, "student_model_training_data", "Knowledge transferred from a larger teacher model to a smaller student model"

    # --- Operational & Interaction Artefacts ---
    SESSION_LOG = "session_log", 160, "interaction_history,conversation_log", "A record of an entire interaction session with an LLM"
    USER_FEEDBACK = "user_feedback", 161, "rating,correction,user_satisfaction_signal", "Feedback provided by the user on the LLM's performance or output"
    ERROR_LOG = "error_log", 162, "exception_trace,failure_report", "Record of errors or exceptions encountered during processing"
    USAGE_STATISTICS = "usage_statistics", 163, "api_calls,token_count,latency_metrics", "Data related to the usage of the LLM or system"
    PROMPT_VERSION = "prompt_version", 164, "prompt_revision,template_id_version", "Identifier for a specific version of a prompt or prompt template"
    MODEL_VERSION = "model_version", 165, "model_id_version,checkpoint_tag", "Identifier for a specific version or instance of an LLM"
    AGENT_OBSERVATION = "agent_observation", 170, "environment_state_for_agent", "Information an LLM-based agent receives from its environment (e.g., result of a tool use)"
    AGENT_ACTION = "agent_action", 171, "llm_agent_decision", "An action taken by an LLM-based agent (e.g., call a tool, respond to user)"
    AGENT_SCRATCHPAD = "agent_scratchpad", 172, "agent_internal_monologue,thought_process_for_agent", "Intermediate thoughts or notes an agent uses to decide on an action"

    # --- Security & Safety ---
    FILTERED_CONTENT = "filtered_content", 180, "sanitized_output,moderated_text", "Content that has been modified or removed due to safety filters or moderation"
    SAFETY_RATING = "safety_rating", 181, "content_safety_score,harm_classification", "A classification or score related to the safety of content (e.g., hate speech, PII)"
    PII_MASKED_TEXT = "pii_masked_text", 182, "anonymized_text,redacted_data", "Text where Personally Identifiable Information has been masked or removed"
    TOXICITY_SCORE = "toxicity_score", 183, "harmful_content_level", "A score indicating the level of toxicity in a piece of text"

    # --- Multimodal (though LLM often implies text, extending a bit) ---
    IMAGE_INPUT = "image_input", 190, "visual_prompt_element", "An image provided as input to a multimodal model"
    AUDIO_INPUT = "audio_input", 191, "speech_input_for_llm", "Audio data provided as input (e.g., for speech-to-text then LLM)"
    VIDEO_INPUT = "video_input", 192, "visual_dynamic_prompt", "Video data provided as input to a multimodal model"
    IMAGE_CAPTION = "image_caption", 193, "generated_image_description", "A textual description of an image, potentially generated by a model"
    AUDIO_TRANSCRIPT = "audio_transcript", 194, "speech_to_text_output", "Text transcribed from audio input"

    # --- Caching & Intermediate ---
    CACHE_ENTRY = "cache_entry", 200, "cached_response,memoized_result", "A stored result of a previous computation or LLM call to speed up future requests"
    INTERMEDIATE_RESULT = "intermediate_result", 201, "pipeline_step_output,partial_computation", "Output from one step in a multi-step process that serves as input to the next"

    # --- Specialized NLP Tasks Outputs ---
    DEPENDENCY_PARSE = "dependency_parse", 210, "syntactic_dependencies", "Syntactic dependency relations between words in a sentence"
    CONSTITUENCY_PARSE = "constituency_parse", 211, "phrase_structure_tree", "Hierarchical syntactic structure of a sentence"
    COREFERENCE_RESOLUTION_CHAINS = "coreference_resolution_chains", 212, "anaphora_resolution", "Chains of mentions referring to the same entity"
    RELATION_EXTRACTION_TUPLE = "relation_extraction_tuple", 213, "semantic_triplet", "Extracted relationships between entities (e.g., <subject, predicate, object>)"
    SEMANTIC_ROLE_LABELS = "semantic_role_labels", 214, "srl_output", "Labels identifying the roles of constituents with respect to a predicate"
    TEXT_DIFFICULTY_SCORE = "text_difficulty_score", 215, "readability_index", "A score indicating the complexity or readability of a text."

    # --- Legal & Compliance ---
    AUDIT_LOG = "audit_log", 220, "compliance_record,transaction_log", "A log for auditing purposes, tracking actions and data access."
    CONSENT_RECORD = "consent_record", 221, "user_agreement_proof", "A record indicating user consent for data usage or specific actions."

    # --- Prompt/Response Management ---
    PROMPT_RESPONSE_PAIR = "prompt_response_pair", 230, "interaction_tuple, qa_pair", "A pairing of a specific prompt and the model's response to it."
    CONVERSATION_HISTORY = "conversation_history", 231, "dialog_context, chat_log_for_prompt", "The sequence of turns in a conversation used as context for the next turn."
    PROMPT_METADATA = "prompt_metadata", 232, "prompt_attributes, prompt_tags", "Additional information about a prompt, like its source, purpose, or version."
    RESPONSE_METADATA = "response_metadata", 233, "output_attributes, generation_details", "Additional information about a response, like model used, latency, token count."

    # --- Artefacts from the LLM training/building process itself ---
    TOKENIZER_MODEL = "tokenizer_model", 240, "bpe_model, sentencepiece_model", "The model used for tokenizing text (e.g., BPE, WordPiece, SentencePiece files)."
    VOCABULARY_FILE = "vocabulary_file", 241, "token_list, vocab_txt", "File listing all tokens in the model's vocabulary."
    TRAINING_SCRIPT = "training_script", 242, "model_training_code", "The code used to train or fine-tune the LLM."
    EVALUATION_SCRIPT = "evaluation_script", 243, "benchmark_code, metrics_calculation_code", "The code used to evaluate the LLM's performance."
    DATA_PREPROCESSING_SCRIPT = "data_preprocessing_script", 244, "data_cleaning_code, data_transformation_code", "Code used to prepare data for training or inference."
    LOSS_CURVE_DATA = "loss_curve_data", 245, "training_loss_history, validation_loss_history", "Data points representing training/validation loss over epochs/steps."
    LEARNING_RATE_SCHEDULE = "learning_rate_schedule", 246, "lr_policy", "The configuration for how the learning rate changes during training."

    # --- User Interface / User Experience related ---
    UI_ELEMENT_STATE = "ui_element_state", 250, "widget_config, form_values", "State of UI elements that might influence prompt generation or display results."
    USER_PROFILE = "user_profile", 251, "user_preferences, personalization_data", "Information about the user that can be used to tailor LLM interactions."

    # --- Artefacts related to explaining LLM behavior ---
    EXPLANATION = "explanation", 260, "xai_output, interpretability_report", "Output from an explainability technique (e.g., LIME, SHAP) detailing why a model made a certain prediction."
    SALIENCY_MAP = "saliency_map", 261, "feature_importance_heatmap, attention_visualization", "A visualization highlighting which parts of the input were most influential for the output."
    COUNTERFACTUAL_EXAMPLE = "counterfactual_example", 262, "what_if_scenario, minimal_change_example", "A slightly modified input that leads to a different desired output, used for explanation or debugging."

    # --- Graph-based Artefacts (e.g. for Knowledge Graphs or complex reasoning) ---
    GRAPH_REPRESENTATION = "graph_representation", 270, "knowledge_graph_subset, node_edge_list", "Data structured as a graph, possibly used as input or generated as output."
    SUBGRAPH_QUERY = "subgraph_query", 271, "sparql_query_for_llm, cypher_query_for_llm", "A query to retrieve a subgraph from a larger graph database, potentially generated by an LLM."
    PATH_IN_GRAPH = "path_in_graph", 272, "reasoning_path, entity_relation_chain", "A sequence of nodes and edges in a graph, potentially representing a reasoning path."

    # --- Final catch-all for things too specific or new to categorize yet ---
    DOMAIN_SPECIFIC_ARTEFACT = "domain_specific_artefact", 998, "custom_type", "An artefact type specific to a particular application domain not covered generally."
    # UNKNOWN is already defined: "unknown", 1, "undefined,unidentified", "Llm Artefact type could not be identified"




class LlmArtefactTypes(BaseEnumMeta):
    # --- Core & Foundational ---
    _INTERNAL_NONE = "internal_none", -1, "_none", "Internal placeholder for no specific language/artefact"
    NONE = "none", 0, "null,nil", "No specific artefact type selected or applicable"
    UNKNOWN = "unknown", 999, "unidentified,other", "Llm Artefact type could not be identified or is not listed"

    # --- Input & Prompting (PE Focus) ---
    INPUT = "input", 1, "raw_input,user_query", "Raw input data or query from the user/system before processing"
    PROMPT = "prompt", 2, "instruction,full_prompt", "The complete textual instruction given to the LLM"
    PROMPT_TEMPLATE = "prompt_template", 3, "template,prompt_structure", "A parameterized structure for generating prompts"
    SYSTEM_PROMPT = "system_prompt", 4, "system_message,persona_prompt", "Instructions setting the LLM's behavior, persona, or role"
    USER_PROMPT = "user_prompt", 5, "user_message,query_prompt", "The specific question or task from the user within a conversation"
    CONTEXT = "context", 6, "retrieved_context,background_info", "Supporting information or documents provided to the LLM with the prompt (e.g., RAG)"
    FEW_SHOT_EXAMPLE = "few_shot_example", 7, "in_context_example,demonstration", "Example input-output pair(s) provided in the prompt for in-context learning"
    EXAMPLE_INPUT = "example_input", 8, "shot_input,demo_input", "The input part of a few-shot example"
    EXAMPLE_OUTPUT = "example_output", 9, "shot_output,demo_output", "The desired output part of a few-shot example"
    PROMPT_PARAMETERS = "prompt_parameters", 10, "template_variables,placeholders", "Variables or parameters used to fill a prompt template"

    # --- LLM Output & Generation ---
    OUTPUT = "output", 20, "llm_response,generation,completion", "The primary textual output generated by the LLM"
    RAW_OUTPUT = "raw_output", 21, "unprocessed_output,model_logits_text", "The direct, unprocessed text from the LLM before any parsing or cleaning"
    PARSED_OUTPUT = "parsed_output", 22, "structured_output,extracted_data", "Output that has been processed or parsed into a structured format (e.g., JSON)"
    CHAIN_OF_THOUGHT = "chain_of_thought", 23, "cot,reasoning_steps", "Intermediate reasoning steps generated by the LLM (can be part of prompt or output)"
    STREAMED_CHUNK = "streamed_chunk", 24, "output_token_stream,partial_response", "A segment of a streamed LLM output"
    FUNCTION_CALL = "function_call", 25, "tool_call,api_request_llm", "LLM output indicating a request to call an external function/tool"
    TOOL_CALL = "tool_call", 26, "agent_tool_call", "A more generic term for LLM-invoked tool usage (often structured)" # Overlaps with FUNCTION_CALL

    # --- Reference & Evaluation ---
    REFERENCE = "reference", 40, "ground_truth,expected_output,label", "The ground truth or target answer/output for evaluation"
    EVALUATION_RESULT = "evaluation_result", 41, "metric_score,assessment", "The outcome of an evaluation, including scores and/or qualitative feedback"
    SCORE = "score", 42, "metric_value,quantitative_eval", "A specific numerical score from an evaluation metric"
    EVALUATION_METRIC = "evaluation_metric", 43, "metric_definition,eval_criteria", "The definition or configuration of a metric used for evaluation (e.g., BLEU, ROUGE)"
    HUMAN_FEEDBACK = "human_feedback", 44, "annotation,human_rating,correction", "Feedback provided by a human annotator or evaluator"
    COMPARISON_RESULT = "comparison_result", 45, "a_b_test_result,preference_data", "Result of comparing two or more LLM outputs or prompts"
    BENCHMARK_DATA = "benchmark_data", 46, "test_suite,standard_eval_set", "A standardized dataset used for benchmarking LLM performance"

    # --- Data & Knowledge ---
    DATASET = "dataset", 60, "corpus,data_collection", "A collection of data used for training, fine-tuning, or evaluation"
    TRAINING_DATA = "training_data", 61, "fine_tuning_set,instruction_set", "Data specifically used for training or fine-tuning an LLM"
    VALIDATION_DATA = "validation_data", 62, "dev_set", "Data used to validate model performance during training/development"
    TEST_DATA = "test_data", 63, "holdout_set", "Data used for final unbiased evaluation of a trained model"
    INSTRUCTION_DATA = "instruction_data", 64, "prompt_response_pairs", "Dataset formatted as instruction-response pairs for fine-tuning"
    KNOWLEDGE_BASE_CHUNK = "knowledge_base_chunk", 65, "document_segment,retrieved_doc", "A chunk or segment from a knowledge base (e.g., for RAG)"
    EMBEDDING_VECTOR = "embedding_vector", 66, "text_embedding,vector_representation", "Numerical vector representation of text"
    TOKEN_SEQUENCE = "token_sequence", 67, "tokenized_text,input_ids", "A sequence of tokens representing text, often as integer IDs"

    # --- Model & Configuration ---
    MODEL_CONFIG = "model_config", 80, "hyperparameters,model_settings", "Configuration parameters for the LLM (e.g., temperature, max_tokens, model_name)"
    MODEL_WEIGHTS = "model_weights", 81, "model_parameters,checkpoint", "The learned parameters or weights of an LLM"
    MODEL_ARCHITECTURE = "model_architecture", 82, "network_structure,model_spec", "Specification of the LLM's architecture"
    TOKENIZER_CONFIG = "tokenizer_config", 83, "tokenizer_settings,vocab_file", "Configuration for the tokenizer, including vocabulary"

    # --- Prompt Engineering Lifecycle & Experimentation ---
    PROMPT_VERSION = "prompt_version", 100, "prompt_iteration", "A specific version or iteration of a prompt"
    EXPERIMENT_CONFIG = "experiment_config", 101, "run_parameters,trial_setup", "Configuration for a PE experiment or run"
    EXPERIMENT_RESULT = "experiment_result", 102, "trial_outcome,run_summary", "Aggregated results and artifacts from a PE experiment"
    PROMPT_CHAIN = "prompt_chain", 103, "sequence_of_prompts,llm_workflow", "A sequence of interconnected prompts or LLM calls"
    AGENT_PLAN = "agent_plan", 104, "task_decomposition,action_sequence", "A plan or sequence of actions generated by an LLM-based agent"
    AGENT_STATE = "agent_state", 105, "scratchpad,memory_context", "The internal state or memory of an LLM-based agent"
    TOOL_DEFINITION = "tool_definition", 106, "function_schema,api_spec_for_llm", "Schema or description of a tool/function available to the LLM"
    TOOL_RESPONSE = "tool_response", 107, "function_output,api_result", "The output or result from executing a tool/function call"

    # --- Operational & Logging ---
    INTERACTION_LOG = "interaction_log", 120, "conversation_history,chat_log", "A log of interactions between a user/system and the LLM"
    ERROR_LOG = "error_log", 121, "exception_trace,failure_report", "Log of errors or exceptions encountered during LLM interaction or processing"
    CACHE_ENTRY = "cache_entry", 122, "cached_response,memoized_result", "A cached LLM response or computation result"
    METADATA = "metadata", 123, "tags,attributes,contextual_info", "Additional information or attributes describing another artefact"

    # --- NLP Specific (pre-LLM or components used by LLMs) ---
    TEXT_DOCUMENT = "text_document", 140, "raw_text,document_content", "A piece of text, like a document or article"
    CORPUS = "corpus", 141, "text_collection,document_set", "A large collection of text documents" # Similar to DATASET but often raw text
    ANNOTATED_TEXT = "annotated_text", 142, "labeled_text,ner_tags,pos_tags", "Text with linguistic annotations (e.g., POS, NER, sentiment)"
    LEXICON = "lexicon", 143, "dictionary,word_list,gazetteer", "A vocabulary or list of words, possibly with associated information"
    GRAMMAR = "grammar", 144, "parsing_rules,syntax_rules", "Formal rules describing the syntax of a language"
    TRANSLATION = "translation", 145, "translated_text", "Text translated from one language to another"
    SUMMARY = "summary", 146, "text_summary,abstract", "A condensed version of a longer text"
    SENTIMENT_LABEL = "sentiment_label", 147, "polarity,emotion_tag", "Label indicating the sentiment (positive, negative, neutral) or emotion"
    TOPIC_MODEL = "topic_model", 148, "lda_result,topic_distribution", "A model representing latent topic in a collection of documents"
    KEYPHRASES = "keyphrases", 149, "keywords,extracted_terms", "Important phrases or terms extracted from text"

    # --- Safety & Guardrails ---
    GUARDRAIL_POLICY = "guardrail_policy", 160, "safety_rules,content_filter_config", "Configuration for safety mechanisms or content filters"
    GUARDRAIL_TRIGGER = "guardrail_trigger", 161, "safety_violation,filter_hit", "Indication that a guardrail or safety filter was activated"
    REDACTED_TEXT = "redacted_text", 162, "sanitized_output,pii_removed", "Text that has had sensitive information removed or masked"
    BIAS_ANALYSIS_REPORT = "bias_analysis_report", 163, "fairness_assessment", "Report detailing analysis of biases in model inputs or outputs"

    # --- Miscellaneous ---
    SESSION_ID = "session_id", 180, "conversation_id,interaction_key", "Identifier for a specific user session or conversation"
    USER_PROFILE = "user_profile", 181, "user_preferences,user_history", "Information about the user interacting with the LLM"
    IMAGE_INPUT = "image_input", 182, "visual_prompt,multimodal_image", "An image provided as input to a multimodal LLM" # For Multimodal
    AUDIO_INPUT = "audio_input", 183, "speech_input,multimodal_audio", "Audio data provided as input to a multimodal LLM" # For Multimodal
    VIDEO_INPUT = "video_input", 184, "visual_audio_prompt,multimodal_video", "Video data provided as input" # For Multimodal
    MULTIMODAL_OUTPUT = "multimodal_output", 185, "image_generation_llm,audio_generation_llm", "Non-textual output from an LLM (e.g., generated image, audio)"