from enum import Enum


class CommandResponseStatus(Enum):
    ACK = 'ACK'
    ERROR_BAD_REQUEST = 'ERROR_BAD_REQUEST'
    JOB_SUBMITTED_QUEUED = 'QUEUED'
    NOT_FOUND = 'NOT_FOUND'
    ERROR_LIMIT_REACHED = 'ERROR_LIMIT_REACHED'
    ERROR_OPERATION_FAILED = 'ERROR_OPERATION_FAILED'
    ERROR_UNKNOWN_COMMAND = 'ERROR_UNKNOWN_COMMAND'
    ERROR_BAD_JSON = 'ERROR_BAD_JSON'
    ERROR_INTERNAL = 'ERROR_INTERNAL'
