from typing import List, Tuple, Final, Dict, Set

GENERAL_PATTERNS: Final[List[str]] = [
    # --- Git ---
    ".git/",                        # Git repository itself (should never be ignored, but good to list)
    ".gitignore",                   # Often good to ensure this isn't accidentally ignored
    ".gitattributes",
    ".gitmodules",

    # --- Compiled files & Build outputs (generic) ---
    "bin/",                         # Compiled binaries
    "obj/",                         # Object files
    "build/",                       # General build output directory
    "dist/",                        # General distribution directory
    "out/",                         # Common output directory
    "target/",                      # Common for Java/Rust build output
    "*.o",                          # Object files
    "*.obj",                        # Object files (Windows)
    "*.so",                         # Shared objects (Linux/Unix)
    "*.dylib",                      # Dynamic libraries (macOS)
    "*.dll",                        # Dynamic Link Libraries (Windows)
    "*.exe",                        # Executables (Windows)
    "*.app",                        # macOS Application bundles
    "*.bundle",                     # macOS bundles
    "*.jar",                        # Java archives
    "*.war",                        # Java web archives
    "*.ear",                        # Java enterprise archives
    "*.a",                          # Static libraries

    # --- Archives & Compressed files (if generated, not source) ---
    "*.zip",
    "*.tar",
    "*.gz",
    "*.tgz",
    "*.rar",
    "*.7z",

    # --- Log files ---
    "*.log",
    "logs/",
    "Log/",
    "logfiles/",

    # --- Temporary files ---
    "*.tmp",
    "*.temp",
    "tmp/",
    "temp/",
    "*~",                           # Backup files from some editors (e.g., Gedit, Kate)
    "*.bak",
    "*.swo",                        # Vim swap files
    "*.swp",                        # Vim swap files
    "*.swx",                        # Vim swap files

    # --- OS-specific files ---
    # macOS
    ".DS_Store",
    ".AppleDouble",
    ".LSOverride",
    "Thumbs.db",                    # Windows thumbnail cache
    "ehthumbs.db",                  # Windows thumbnail cache
    "Desktop.ini",                  # Windows folder customization
    ".Spotlight-V100",
    ".Trashes",
    "__MACOSX/",                    # Resource fork archive

    # --- IDE & Editor specific ---
    # JetBrains (IntelliJ, PyCharm, WebStorm, Rider, CLion, etc.)
    ".idea/",
    "*.iml",                        # IntelliJ module files
    "*.ipr",                        # IntelliJ project files (older format)
    "*.iws",                        # IntelliJ workspace files (older format)
    "out/",                         # Default IntelliJ output dir
    "shelf/",                       # IntelliJ shelf
    ".project",                     # Eclipse project files
    ".classpath",                   # Eclipse classpath files
    ".settings/",                   # Eclipse settings
    # VS Code
    ".vscode/",
    "*.code-workspace",             # VS Code workspace settings (user-specific ones might be ignored)
    # Sublime Text
    "*.sublime-project",
    "*.sublime-workspace",
    # NetBeans
    "nbproject/",
    "build.xml",                    # Ant build script (if generated by Netbeans and not primary)
    "nbbuild/",
    "dist/",                        # NetBeans dist output
    "nbdist/",
    ".nb-gradle/",
    # Atom
    ".atom/",
    # Emacs
    "*~",
    "#*#",
    ".#*",
    # Vim
    "[._]*.s[a-v][a-z]",
    "!*.svg", # Keep .svg files if they start with .s
    "*.un~",
    "Session.vim",
    ".netrwhist",

    # --- Dependency & Package Manager Caches/Directories ---
    "node_modules/",                # Node.js
    "jspm_packages/",               # JSPM
    "bower_components/",            # Bower
    ".npm",                         # NPM cache
    ".yarnclean",                   # Yarn
    ".pnp.*",                       # Yarn PnP

    # --- Secrets & Credentials (NEVER commit these!) ---
    ".env",                         # Environment variables
    ".env.*",                       # e.g. .env.local, .env.development
    "!.env.example",                # Allow example env files
    "secrets.*",
    "credentials.*",
    "*.pem",                        # Private keys
    "*.key",
    "*.keychain",
    "config.json",                  # If it contains sensitive data (be careful, sometimes it's template)
    "settings.local.php",           # Drupal local settings
    "local_settings.py",            # Django local settings

    # --- Testing & Coverage ---
    ".coverage",
    ".coverage.*",
    "coverage.xml",
    "htmlcov/",
    "nosetests.xml",
    "pytestdebug.log",
    ".tox/",
    "junit.*",
    "test-results/",
    "test-reports/",

    # --- Virtualization & Containerization ---
    ".vagrant/",
    "Vagrantfile",                  # If user-specific or contains secrets
    ".terraform/",
    "*.tfstate",
    "*.tfstate.*",
    ".dockerignore",                # Similar to .gitignore but for Docker
    # Docker often produces large images/caches; these are not typically in the repo
    # but if build artifacts are somehow placed in project dir:
    # "docker-compose.override.yml", # If user-specific overrides

    # --- Databases (local instances/dumps) ---
    "*.sqlite",
    "*.sqlite3",
    "*.db",
    "*.sql",                        # Be careful, sometimes these are migration scripts
    "dump.rdb",                     # Redis dump

    # --- Miscellaneous ---
    ".project",                     # Generic project file, sometimes by IDEs
    ".cache",
    ".DS_Store?",                   # Handle cases where .DS_Store might have an extension
    "error_log",
    "npm-debug.log*",
    "yarn-debug.log*",
    "yarn-error.log*",
    "hs_err_pid*",                  # Java HotSpot VM error logs
    "replay_pid*",                  # Java HotSpot VM replay logs
]

# ==============================================================================
# PYTHON SPECIFIC (including Poetry)
# ==============================================================================
PYTHON_PATTERNS: Final[List[str]] = [
    # --- Python Virtual Environments ---
    ".venv/",
    "venv/",
    "ENV/",
    "env/",
    "virtualenv/",
    "venv.bak/",
    ".direnv/",                     # For direnv users

    # --- Python Bytecode and Caches ---
    "*.pyc",
    "*.pyo",
    "*.pyd",
    "__pycache__/",
    ".python-version",              # pyenv version file, if you want it repo-specific commit it
    ".pytest_cache/",
    ".mypy_cache/",
    ".dmypy.json",
    "dmypy.json",
    ".pytype/",
    "cython_debug/",
    "profile_output/",

    # --- Distribution / packaging ---
    "*.egg-info/",
    ".eggs/",
    "sdist/",
    "develop-eggs/",
    "parts/",
    "wheels/",
    "pip-wheel-metadata/",
    "*.manifest",
    "MANIFEST",                     # Ensure MANIFEST.in is NOT ignored

    # --- Installers ---
    # Put OS X built Kivy .app bundles in .gitignore:
    "*.app", # Already in general, but good to reiterate if context-specific

    # --- IPython/Jupyter Notebook ---
    ".ipynb_checkpoints/",
    "profile_default/",
    "ipython_config.py",            # If user-specific

    # --- Sphinx documentation ---
    "docs/_build/",
    "docs/build/",                  # Common alternative

    # --- Poetry specific ---
    # Poetry creates virtualenvs in .venv by default (covered)
    # or in a global cache.
    # poetry.lock SHOULD BE COMMITTED.
    # pyproject.toml SHOULD BE COMMITTED.
    # No specific Poetry-generated project files usually need ignoring beyond standard Python ones.
    # However, if you install poetry locally using the old `get-poetry.py` script:
    ".poetry/",                     # Local poetry installation (less common now)

    # --- Ruff (linter/formatter) ---
    ".ruff_cache/",

    # --- PyInstaller ---
    # Usually outputs to dist/ (covered) or a custom dir
    "*.spec", # PyInstaller spec files (sometimes committed, sometimes generated)
]

# ==============================================================================
# UNREAL ENGINE 5 SPECIFIC
# ==============================================================================
# Based on Epic's recommendations and common community practices.
# NOTE: Some of these might overlap with GENERAL_PATTERNS but are listed
#       for explicitness in the UE context.
UNREAL_ENGINE_5_PATTERNS: Final[List[str]] = [
    # --- UE Generated Project Files (Visual Studio, XCode, Rider) ---
    # These are typically generated from .uproject and should not be versioned.
    "*.sln",                        # Visual Studio Solution
    "*.suo",                        # Visual Studio Solution User Options
    "*.xcodeproj",                  # Xcode Project
    "*.xcworkspace",                # Xcode Workspace
    ".vs/",                         # Visual Studio IDE specific (cache, settings)
    "*.VC.db",                      # Visual Studio C++ IntelliSense database
    "*.VC.db-shm",
    "*.VC.db-wal",
    "*.sdf",                        # SQL Server Compact file, sometimes used by VS
    "*.user",                       # User-specific build settings (e.g. MyProject.vcxproj.user)
    "*.vcxproj.filters",            # VS project filters (can be generated)
    # Rider specific (though .idea/ is general, these are more specific)
    ".ideaRider/",                  # Rider specific project files if named differently
    "*.sln.DotSettings",            # Rider solution settings
    "*.sln.DotSettings.user",       # Rider user-specific solution settings
    "*.uproject.DotSettings",       # Rider project settings
    "*.uproject.DotSettings.user",  # Rider user-specific project settings

    # --- UE Build Products & Intermediate Files ---
    "Binaries/",                    # Compiled game/editor binaries
    "Build/",                       # Build scripts and some intermediate outputs (e.g. UBT Makefile)
                                    # Note: Some Build/ scripts (e.g., Build/BatchFiles) might be versioned
                                    # if they are custom. Be selective if needed.
                                    # A common pattern is to ignore Build/* but !Build/some_custom_script.bat
    "DerivedDataCache/",            # Engine's cache for derived assets (HUGE, machine-specific)
    "Intermediate/",                # Intermediate files from compilation and cooking
    "Saved/",                       # Saved data like logs, configs, screenshots, autosaves
                                    # Be careful: Saved/Config/Windows/Input.ini or similar might be
                                    # versioned if they contain project-wide default settings.
                                    # More common to ignore:
                                    # "Saved/Autosaves/"
                                    # "Saved/Backup/"
                                    # "Saved/Crashes/"
                                    # "Saved/Logs/"
                                    # "Saved/Cooked/" (if cooking locally and not for distribution)
                                    # "Saved/Sandboxes/"
                                    # "Saved/Screenshots/"
                                    # "Saved/SaveGames/" (unless you want to version example saves)
                                    # "Saved/Config/CrashReportClient/"
                                    # "Saved/Config/Windows/EditorUserSettings.ini" (user specific)
                                    # "Saved/Config/Windows/EditorLayout.ini" (user specific)
                                    # "Saved/Config/Windows/EditorScriptingUtilities.ini" (user specific)
                                    # "Saved/Config/ModKit/" (if using ModKit)

    # --- Platform Specific Build Outputs (if building locally into project dir) ---
    "*-Win64-Debug.*",
    "*-Win64-Development.*",
    "*-Win64-Shipping.*",
    "*-Mac-Debug.*",
    "*-Mac-Development.*",
    "*-Mac-Shipping.*",
    # Add other platforms as needed (Linux, Android, iOS, etc.)
    "*.apk",                        # Android package
    "*.ipa",                        # iOS package

    # --- Other UE Related ---
    ".gradle/",                     # Android build system cache (if building for Android)
    "gradle/",                      # Android Gradle wrapper
    "gradlew",
    "gradlew.bat",
    "local.properties",             # Android local properties (SDK path etc.)
    "csharp.project.json",          # If using C# plugins with older systems
    "*.pidb",                       # Program Database File, alternative to PDB
    "*.pdb",                        # Program Database File (debug symbols) - sometimes committed for crash dumps
                                    # but often large and build-specific.
    "Template_UFS/",                # Universal File System template

    # --- UE Plugins (sometimes have their own intermediate/binary folders) ---
    # This is highly plugin-specific, but if a plugin creates junk:
    # "Plugins/MyPlugin/Binaries/",
    # "Plugins/MyPlugin/Intermediate/",

    # --- Visual Assist X (common VS plugin for C++) ---
    ".va/",

    # --- Source Control Specific (if using built-in UE SCC and it drops files) ---
    # Usually handled by the SCC provider's ignore file (e.g. .p4ignore)
    # but sometimes temporary files might appear.
]



_combined_set = set()
_combined_set.update(GENERAL_PATTERNS)
_combined_set.update(PYTHON_PATTERNS)
_combined_set.update(UNREAL_ENGINE_5_PATTERNS)


STANDARD_GIT_IGNORE_PATTERNS: Final[List[str]] = sorted(list(_combined_set))

PREFERRED_ENCODINGS: Final[Tuple[str, ...]] = ('utf-8', 'latin-1')



STANDARD_GIT_IGNORE_PATTERNS_SET = set(f"{e}" for e in STANDARD_GIT_IGNORE_PATTERNS)

ALLOWED_FILES_FOR_VERSIONING: Set[str] = {"py","cpp","odin","h"}