from collections import defaultdict
from dataclasses import field, dataclass
from enum import Enum
from pathlib import Path
from typing import List, Tuple, Dict


class LicenseType(Enum):
    NONE = "none"
    COPYRIGHT = "copyright"
    MIT = "mit"


class ReadmeType(Enum):
    NONE = "none"
    MINIMAL = "minimal"
    STANDARD = "standard"
    FULL = "full"

# Holds all configuration and data for a specific project instance being created.
@dataclass()
class ProjectData:
    name: str
    description: str = "Module for Minir"
    author_name: str = "silenterus"
    author_mail: str = "neo-neu@web.de"
    name_prefix: str = "minir_"

    version: str = "0.1.0"


    prompt: str = "" # If prompt is supplied, potentially trigger different template/post-processing later

    # Console application configuration:
    # - []: Treat as a library/module (no main entry point generated by default template).
    # - ["main"]: Standard console app (e.g., if __name__ == "__main__" or simple Click command).
    # - ["cmd1", "cmd2"]: Multi-command CLI app (template should support Click groups).
    console: List[str] = field(default_factory=lambda: ["main"])

    script_command: str = ""
    name_method_appendix: str = "er"

    name_console_method_appendix: str = "_exec"


    # Conditional inclusion flags:
    include_pycharm_folder: bool = True
    include_tests: bool = True

    readme:ReadmeType = ReadmeType.NONE
    license:LicenseType = LicenseType.NONE


    python_version: str = "3.11.3"

    dependencies: Dict[str,str] = field(default_factory=lambda: {
        "pytest": "^8.3.0",
        "pytest-cov": "^3.0.0",
        "mypy": "^1.15.0",
        "pyright": "^1.1.370",
        "pyinstaller": "^6.13.0",
        "poetry-core": ">=2.0.0,<3.0.0",
    })
    dev_dependencies: Dict[str,str] = field(default_factory=dict)

    # Base directory for placing the generated project folder
    output_base_dir: Path = Path(".")

    @property
    def full_project_name(self) -> str:
        """Calculates the full project name including the prefix."""
        return f"{self.name_prefix}{self.name}"

    @property
    def method_name(self) -> str:
        return f"{self.name}{self.name_method_appendix}"



    @property
    def init_imports(self) -> str:
        all_imports = ""
        if len(self.console) > 0 and self.console[0] != "main":
            for imports in self.console:
                all_imports += f"\nfrom .{imports} import {imports}{self.name_console_method_appendix}"

        else:
            all_imports = f"from .{self.name} import {self.name_method_appendix}"
        return all_imports

    @property
    def init_public(self) -> str:
        if len(self.console) > 0 and self.console[0] != "main":
            publics = []
            for public in self.console:
                publics.append(f"{public}{self.name_console_method_appendix}")

            all_temp = "','".join(publics)
            all_publics = f"__all__ = ['{all_temp}']"
            pass
        else:
            all_publics = f"__all__ = ['{self.name_method_appendix}']"


        return all_publics

    @property
    def poetry_dependencies_dev(self) -> str:
        return self._poetry_dependencies_build()

    @property
    def poetry_dependencies(self) -> str:
        return self._poetry_dependencies_build(True)


    def _poetry_dependencies_build(self, dev:bool = False) -> str:

        if dev:
            selected = self.dev_dependencies.items()
        else:
            selected = self.dependencies.items()

        if len(selected) > 0:
            has_dependencies = ""
            for d_key, d_item in selected:
                has_dependencies += f"\n{d_key} = \"{d_item}\""
        else:
            has_dependencies = ""


        return has_dependencies

    @property
    def poetry_click_build(self, dev: bool = False) -> str:
        return ""


    @property
    def output_dir(self) -> Path:
        """Calculates the final output directory path for the project."""
        return (self.output_base_dir / self.full_project_name).resolve()

